"""
Setup script for OpenAI API integration
Run this to configure your OpenAI API key
"""

import os
import sys

def setup_openai_api():
    print("=" * 60)
    print("🤖 GPT-4 Healthcare Chatbot Setup")
    print("=" * 60)
    print()
    
    print("To use the ChatGPT-like healthcare assistant, you need an OpenAI API key.")
    print()
    print("How to get your API key:")
    print("1. Go to https://platform.openai.com/api-keys")
    print("2. Sign up or log in to your OpenAI account")
    print("3. Click 'Create new secret key'")
    print("4. Copy the key (it starts with 'sk-')")
    print()
    
    api_key = input("Enter your OpenAI API key: ").strip()
    
    if not api_key:
        print("❌ No API key provided. Exiting...")
        return False
    
    if not api_key.startswith('sk-'):
        print("⚠️  Warning: API keys usually start with 'sk-'")
        confirm = input("Continue anyway? (y/n): ").lower()
        if confirm != 'y':
            return False
    
    # Save to .env file
    env_path = os.path.join(os.path.dirname(__file__), '.env')
    
    # Read existing .env content
    env_content = {}
    if os.path.exists(env_path):
        with open(env_path, 'r') as f:
            for line in f:
                if '=' in line and not line.startswith('#'):
                    key, value = line.strip().split('=', 1)
                    env_content[key] = value
    
    # Update with OpenAI key
    env_content['OPENAI_API_KEY'] = api_key
    
    # Write back to .env
    with open(env_path, 'w') as f:
        f.write("# Healthcare Chatbot Environment Variables\n")
        f.write("# Generated by setup_openai.py\n\n")
        for key, value in env_content.items():
            f.write(f"{key}={value}\n")
    
    print()
    print("✅ API key saved successfully!")
    print(f"📁 Saved to: {env_path}")
    print()
    print("You can now run your healthcare chatbot with GPT-4 powered responses!")
    print("Restart the server to apply the changes.")
    print()
    
    # Set for current session
    os.environ['OPENAI_API_KEY'] = api_key
    
    return True

def test_api_key():
    """Test if the API key works"""
    api_key = os.getenv('OPENAI_API_KEY')
    
    if not api_key:
        print("❌ No API key found in environment")
        return False
    
    try:
        from openai import OpenAI
        client = OpenAI(api_key=api_key)
        
        print("🔄 Testing API key...")
        
        # Make a simple test request
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": "Hello"}],
            max_tokens=10
        )
        
        print("✅ API key is valid!")
        print(f"🤖 Model: GPT-4 Mini")
        print()
        return True
        
    except Exception as e:
        print(f"❌ API key test failed: {e}")
        print()
        print("Common issues:")
        print("- Invalid API key format")
        print("- API key has been revoked")
        print("- No internet connection")
        print("- OpenAI service is down")
        return False

if __name__ == '__main__':
    print()
    
    # Check if API key already exists
    existing_key = os.getenv('OPENAI_API_KEY')
    
    if existing_key:
        print("🔑 OpenAI API key already configured!")
        print()
        test_api_key()
        
        choice = input("Do you want to update the API key? (y/n): ").lower()
        if choice != 'y':
            print("Keeping existing configuration.")
            sys.exit(0)
    
    # Setup new API key
    if setup_openai_api():
        test_api_key()
