"""
Medicine Database with comprehensive medicine information
Data sourced from common pharmaceutical databases and 1mg.com patterns
"""

def get_medicine_database():
    """Return comprehensive medicine database"""
    return [
        {
            'id': 'para500',
            'name': 'Paracetamol 500mg',
            'manufacturer': 'GSK Pharmaceuticals',
            'category': 'pain_relief',
            'type': 'tablet',
            'usage': 'Used for relief of pain and fever. Effective for headaches, muscle aches, arthritis, backache, toothaches, colds, and fevers.',
            'dosage': 'Adults: 1-2 tablets every 4-6 hours. Maximum 8 tablets in 24 hours. Take with water after food.',
            'price': 25,
            'package_size': '10 tablets',
            'popularity': 98,
            'tags': ['fever', 'headache', 'pain', 'cold'],
            'side_effects': ['Nausea', 'Stomach upset', 'Rare: Liver damage (with overdose)', 'Allergic reactions'],
            'warnings': ['Do not exceed recommended dose', 'Avoid alcohol while taking', 'Consult doctor if you have liver disease', 'Not for children under 12 without medical advice'],
            'storage': 'Store below 25°C in a dry place'
        },
        {
            'id': 'ibu400',
            'name': 'Ibuprofen 400mg',
            'manufacturer': 'Cipla Ltd',
            'category': 'pain_relief',
            'type': 'tablet',
            'usage': 'Non-steroidal anti-inflammatory drug (NSAID) used for pain relief, reducing inflammation, and lowering fever. Effective for arthritis, menstrual cramps, and dental pain.',
            'dosage': 'Adults: 1 tablet 3 times daily after meals. Maximum 1200mg per day. Take with food to reduce stomach upset.',
            'price': 45,
            'package_size': '10 tablets',
            'popularity': 92,
            'tags': ['pain', 'inflammation', 'arthritis', 'fever'],
            'side_effects': ['Stomach pain', 'Heartburn', 'Nausea', 'Dizziness', 'Rare: Stomach bleeding'],
            'warnings': ['Take with food', 'Avoid if you have stomach ulcers', 'Not recommended during pregnancy', 'Consult doctor if you have kidney or heart problems'],
            'storage': 'Store in original container below 30°C'
        },
        {
            'id': 'amox500',
            'name': 'Amoxicillin 500mg',
            'manufacturer': 'Alkem Laboratories',
            'category': 'antibiotics',
            'type': 'capsule',
            'usage': 'Penicillin-type antibiotic used to treat bacterial infections including respiratory tract infections, urinary tract infections, skin infections, and ear infections.',
            'dosage': 'Adults: 1 capsule 3 times daily (every 8 hours) for 7-10 days. Complete full course even if symptoms improve.',
            'price': 120,
            'package_size': '10 capsules',
            'popularity': 88,
            'tags': ['antibiotic', 'infection', 'bacterial'],
            'side_effects': ['Diarrhea', 'Nausea', 'Rash', 'Vomiting', 'Yeast infection'],
            'warnings': ['Complete full course', 'Do not use for viral infections', 'Inform doctor of penicillin allergy', 'May reduce effectiveness of birth control pills'],
            'storage': 'Store below 25°C away from moisture'
        },
        {
            'id': 'cetzine10',
            'name': 'Cetirizine 10mg',
            'manufacturer': 'Dr. Reddys Laboratories',
            'category': 'cold_flu',
            'type': 'tablet',
            'usage': 'Antihistamine used to relieve allergy symptoms such as runny nose, sneezing, watery eyes, and itching. Also used for hives and skin rashes.',
            'dosage': 'Adults: 1 tablet once daily. Can be taken with or without food. May cause drowsiness.',
            'price': 35,
            'package_size': '10 tablets',
            'popularity': 85,
            'tags': ['allergy', 'cold', 'runny nose', 'sneezing'],
            'side_effects': ['Drowsiness', 'Dry mouth', 'Fatigue', 'Headache', 'Sore throat'],
            'warnings': ['May cause drowsiness - avoid driving', 'Avoid alcohol', 'Consult doctor if pregnant', 'Use caution in kidney disease'],
            'storage': 'Store below 30°C in a dry place'
        },
        {
            'id': 'omep20',
            'name': 'Omeprazole 20mg',
            'manufacturer': 'Sun Pharmaceutical',
            'category': 'digestive',
            'type': 'capsule',
            'usage': 'Proton pump inhibitor used to treat acid reflux, GERD, stomach ulcers, and heartburn. Reduces stomach acid production.',
            'dosage': 'Adults: 1 capsule once daily before breakfast. Swallow whole, do not crush or chew. Take 30 minutes before eating.',
            'price': 95,
            'package_size': '10 capsules',
            'popularity': 82,
            'tags': ['acidity', 'reflux', 'stomach', 'ulcer'],
            'side_effects': ['Headache', 'Nausea', 'Diarrhea', 'Stomach pain', 'Gas'],
            'warnings': ['Take before meals', 'Do not crush capsules', 'Long-term use may affect bone health', 'Inform doctor if symptoms persist'],
            'storage': 'Store below 25°C away from light'
        },
        {
            'id': 'metform500',
            'name': 'Metformin 500mg',
            'manufacturer': 'USV Ltd',
            'category': 'diabetes',
            'type': 'tablet',
            'usage': 'Oral diabetes medication used to control blood sugar levels in type 2 diabetes. Helps improve insulin sensitivity and reduces glucose production.',
            'dosage': 'Usually started at 500mg twice daily with meals. Dose may be gradually increased by doctor based on blood sugar levels.',
            'price': 55,
            'package_size': '10 tablets',
            'popularity': 90,
            'tags': ['diabetes', 'blood sugar', 'type 2'],
            'side_effects': ['Nausea', 'Diarrhea', 'Stomach upset', 'Metallic taste', 'Loss of appetite'],
            'warnings': ['Take with meals', 'Monitor blood sugar regularly', 'Avoid alcohol', 'Inform doctor of kidney problems', 'May cause vitamin B12 deficiency'],
            'storage': 'Store below 30°C in a dry place'
        },
        {
            'id': 'amlodipine5',
            'name': 'Amlodipine 5mg',
            'manufacturer': 'Pfizer Ltd',
            'category': 'heart',
            'type': 'tablet',
            'usage': 'Calcium channel blocker used to treat high blood pressure and angina (chest pain). Helps relax blood vessels for better blood flow.',
            'dosage': 'Adults: 1 tablet once daily with or without food. Take at the same time each day. Do not stop suddenly without consulting doctor.',
            'price': 75,
            'package_size': '10 tablets',
            'popularity': 86,
            'tags': ['blood pressure', 'hypertension', 'heart', 'angina'],
            'side_effects': ['Swelling of ankles', 'Dizziness', 'Flushing', 'Fatigue', 'Palpitations'],
            'warnings': ['Do not stop suddenly', 'Monitor blood pressure regularly', 'Avoid grapefruit juice', 'Use caution in liver disease'],
            'storage': 'Store below 25°C away from light'
        },
        {
            'id': 'dolo650',
            'name': 'Dolo 650mg',
            'manufacturer': 'Micro Labs Ltd',
            'category': 'pain_relief',
            'type': 'tablet',
            'usage': 'Paracetamol-based pain reliever and fever reducer. Used for headaches, body pain, toothache, and fever. More potent than regular 500mg paracetamol.',
            'dosage': 'Adults: 1 tablet every 6 hours as needed. Maximum 4 tablets in 24 hours. Take with water after food.',
            'price': 30,
            'package_size': '15 tablets',
            'popularity': 95,
            'tags': ['fever', 'pain', 'headache', 'covid'],
            'side_effects': ['Nausea', 'Allergic reactions', 'Rare: Liver damage (overdose)'],
            'warnings': ['Do not exceed 4 tablets daily', 'Avoid alcohol', 'Consult doctor for use beyond 3 days', 'Keep away from children'],
            'storage': 'Store below 25°C in a dry place'
        },
        {
            'id': 'azithro500',
            'name': 'Azithromycin 500mg',
            'manufacturer': 'Alembic Pharmaceuticals',
            'category': 'antibiotics',
            'type': 'tablet',
            'usage': 'Macrolide antibiotic used to treat respiratory infections, skin infections, ear infections, and sexually transmitted diseases.',
            'dosage': 'Usually 500mg once daily for 3 days or as directed by doctor. Take 1 hour before or 2 hours after meals.',
            'price': 150,
            'package_size': '3 tablets',
            'popularity': 87,
            'tags': ['antibiotic', 'respiratory', 'infection'],
            'side_effects': ['Diarrhea', 'Nausea', 'Stomach pain', 'Vomiting', 'Headache'],
            'warnings': ['Complete full course', 'Take on empty stomach', 'Inform doctor of liver problems', 'May cause heart rhythm issues'],
            'storage': 'Store below 30°C away from moisture'
        },
        {
            'id': 'pantocid40',
            'name': 'Pantocid 40mg (Pantoprazole)',
            'manufacturer': 'Alkem Laboratories',
            'category': 'digestive',
            'type': 'tablet',
            'usage': 'Proton pump inhibitor for treating acid reflux, GERD, stomach ulcers, and Zollinger-Ellison syndrome. Reduces stomach acid production.',
            'dosage': 'Adults: 1 tablet once daily before breakfast. Swallow whole. Treatment duration usually 4-8 weeks.',
            'price': 110,
            'package_size': '10 tablets',
            'popularity': 84,
            'tags': ['acidity', 'reflux', 'GERD', 'ulcer'],
            'side_effects': ['Headache', 'Diarrhea', 'Nausea', 'Joint pain', 'Dizziness'],
            'warnings': ['Take before meals', 'Do not crush', 'Long-term use may increase fracture risk', 'May mask stomach cancer symptoms'],
            'storage': 'Store below 25°C in original packaging'
        },
        {
            'id': 'becosules',
            'name': 'Becosules Capsules',
            'manufacturer': 'Pfizer Ltd',
            'category': 'vitamins',
            'type': 'capsule',
            'usage': 'Vitamin B-complex supplement used to prevent and treat vitamin B deficiency. Supports energy metabolism, nerve function, and overall health.',
            'dosage': 'Adults: 1 capsule daily after meals with water. Can be taken long-term as directed by doctor.',
            'price': 40,
            'package_size': '20 capsules',
            'popularity': 80,
            'tags': ['vitamins', 'B-complex', 'energy', 'supplement'],
            'side_effects': ['Rare: Nausea', 'Allergic reactions', 'Bright yellow urine (harmless)'],
            'warnings': ['Do not exceed recommended dose', 'Not a substitute for balanced diet', 'Consult doctor if pregnant', 'May interact with certain medications'],
            'storage': 'Store below 25°C away from moisture'
        },
        {
            'id': 'cough_syrup',
            'name': 'Benadryl Cough Syrup',
            'manufacturer': 'Johnson & Johnson',
            'category': 'cold_flu',
            'type': 'syrup',
            'usage': 'Cough suppressant and antihistamine for relief of dry cough, allergic cough, and throat irritation. Provides soothing relief.',
            'dosage': 'Adults: 10ml (2 teaspoons) 3-4 times daily. Children: As directed by pediatrician. Do not exceed recommended dose.',
            'price': 85,
            'package_size': '100ml',
            'popularity': 78,
            'tags': ['cough', 'cold', 'allergy', 'throat'],
            'side_effects': ['Drowsiness', 'Dizziness', 'Dry mouth', 'Blurred vision'],
            'warnings': ['May cause drowsiness', 'Avoid driving', 'Not for children under 6 without doctor advice', 'Avoid alcohol'],
            'storage': 'Store below 25°C. Do not freeze.'
        },
        {
            'id': 'betadine',
            'name': 'Betadine Ointment',
            'manufacturer': 'Win-Medicare',
            'category': 'antibiotics',
            'type': 'cream',
            'usage': 'Antiseptic ointment for preventing infection in cuts, wounds, burns, and minor skin injuries. Contains povidone-iodine.',
            'dosage': 'Apply thin layer to affected area 2-3 times daily. Clean wound before application. Cover with bandage if needed.',
            'price': 65,
            'package_size': '20g',
            'popularity': 76,
            'tags': ['antiseptic', 'wound', 'infection', 'first aid'],
            'side_effects': ['Skin irritation', 'Rare: Allergic reaction', 'Staining of skin'],
            'warnings': ['For external use only', 'Do not use on deep wounds', 'Avoid eyes', 'Discontinue if irritation occurs', 'Not for iodine-allergic patients'],
            'storage': 'Store below 25°C away from light'
        },
        {
            'id': 'shelcal500',
            'name': 'Shelcal 500mg',
            'manufacturer': 'Alkem Laboratories',
            'category': 'vitamins',
            'type': 'tablet',
            'usage': 'Calcium and Vitamin D3 supplement for bone health, osteoporosis prevention, and calcium deficiency. Supports strong bones and teeth.',
            'dosage': 'Adults: 1 tablet once or twice daily after meals. Chew thoroughly before swallowing for better absorption.',
            'price': 115,
            'package_size': '15 tablets',
            'popularity': 83,
            'tags': ['calcium', 'vitamin D', 'bones', 'osteoporosis'],
            'side_effects': ['Constipation', 'Bloating', 'Gas', 'Nausea'],
            'warnings': ['Do not exceed recommended dose', 'Take with food', 'Consult doctor if you have kidney stones', 'Maintain adequate fluid intake'],
            'storage': 'Store below 25°C in a dry place'
        },
        {
            'id': 'crocin_syrup',
            'name': 'Crocin Pediatric Syrup',
            'manufacturer': 'GSK Pharmaceuticals',
            'category': 'pain_relief',
            'type': 'syrup',
            'usage': 'Paracetamol-based fever and pain relief syrup specially formulated for children. Used for fever, teething pain, and post-vaccination fever.',
            'dosage': 'Children 1-3 years: 5ml. 4-8 years: 10ml. 9-12 years: 15ml. Every 4-6 hours as needed. Use measuring cup provided.',
            'price': 70,
            'package_size': '60ml',
            'popularity': 89,
            'tags': ['children', 'fever', 'pain', 'paracetamol'],
            'side_effects': ['Rare: Allergic reactions', 'Nausea', 'Liver damage (only with overdose)'],
            'warnings': ['Use only measuring cup provided', 'Do not exceed 4 doses in 24 hours', 'Keep away from children', 'Consult doctor if fever persists'],
            'storage': 'Store below 25°C. Do not use after 3 months of opening.'
        }
    ]
